[package]
name = "armyknife"
description = "A collection of useful command-line tools"
license-file = "LICENSE.txt"
version = "0.3.0"
edition = "2024"
repository = "https://github.com/jwoo0122/armyknife"

[dependencies]
urlencoding = "2.1.3"
git2 = "0.20.2"
